name: MofuAssistant
version: '${version}'
main: page.nafuchoco.mofu.mofuassistant.MofuAssistant
api-version: 1.17
authors: [ NAFU_at ]
website: https://github.com/mofucraft
softdepend: [LuckPerms]

commands:
  peaceful:
    description: Experience a simulated Peaceful Mode.

  assistant:
    description: Configure settings related to plugins.

  migrate:
    description: Migrate player data.

  osusowaken:
    description: Community item distribution system.

permissions:
  mofuassistant.assistant:
    description: Allows you to use the assistant command.
    default: op

  mofuassistant.peaceful:
    description: Allows you to use the peaceful command.
    default: op

  mofuassistant.migrate:
    description: Allows you to migrate player data.
    default: false

  mofuassistant.osusowaken:
    description: Allows you to use the osusowaken command.
    default: true

  mofuassistant.osusowaken.admin:
    description: Allows you to manage the osusowaken system.
    default: op
