name: MofuAssistant
version: '${version}'
main: page.nafuchoco.mofu.mofuassistant.MofuAssistant
api-version: 1.17
authors: [ NAFU_at ]
website: https://github.com/mofucraft
softdepend: [LuckPerms]

commands:
  peaceful:
    description: Experience a simulated Peaceful Mode.

  assistant:
    description: Configure settings related to plugins.

  migrate:
    description: Migrate player data.

  osusowaken:
    description: Community item distribution system.

  co-invite:
    description: Invite a player to your community.
    usage: /co-invite <player> <communityId>

  co-cancel:
    description: Cancel an invite to a player.
    usage: /co-cancel <player> <communityId>

  co-check:
    description: Check your pending invites.

  co-check-o:
    description: Check another player's pending invites.
    usage: /co-check-o <player>

  co-accept:
    description: Accept a community invite.
    usage: /co-accept <communityId>

  co-deny:
    description: Deny a community invite.
    usage: /co-deny <communityId>

  co-leave:
    description: Leave a community.
    usage: /co-leave <communityId>

  co-who:
    description: List members of a community.
    usage: /co-who <communityId> [page]

permissions:
  mofuassistant.assistant:
    description: Allows you to use the assistant command.
    default: op

  mofuassistant.peaceful:
    description: Allows you to use the peaceful command.
    default: op

  mofuassistant.migrate:
    description: Allows you to migrate player data.
    default: false

  mofuassistant.osusowaken:
    description: Allows you to use the osusowaken command.
    default: true

  mofuassistant.osusowaken.admin:
    description: Allows you to manage the osusowaken system.
    default: op
